#!/usr/bin/env sh

# TODO: Get the directory of the current script
__shell_sources_dir=$(dirname $(readllink -f "$0"))

# Loop through and source sh files in the configs directory
for f in "${__shell_sources_dir}/shell"/*; do
  source "$f"
done
