#!/usr/bin/env bash

bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

__currentusername="$(whoami)"
__desktoppath="$HOME/Desktop"

home() {
    cd ~ || return

    echo "Welcome home, $__currentusername!"
}

desktop() {
    cd "$__desktoppath" || return
}

reload() {
    echo "Reloading..."
    exec $SHELL
}

updatebashconfigs() {
    cd "$__bash_configs_dir" || return
    if git pull
    then
        reload
    fi
    cd - >/dev/null 2>&1 || return
}
